version: '3'

services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME
      # - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - data:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 15s

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    # environment:
      # - ME_CONFIG_MONGODB_ADMINUSERNAME
      # - ME_CONFIG_MONGODB_ADMINPASSWORD
      # - ME_CONFIG_MONGODB_URL
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  data:
